### PR TITLE
Support longer versions instead of just semver

### PR DESCRIPTION
**Pull request by cloudlena**

### CODE REVIEW

**Review by drnic — COMMENTED** [review]
At a glance it looks good. If you're concerned to merge without testing, perhaps push a tagged Docker image and I can try it out in my pipeline for you.

**Comment by cloudlena** [comment]
Done. @drnic, can you test it with the `feature_support-longer-version-numbers` tag from https://hub.docker.com/r/mastertinner/apache-directory-index-resource/tags/?

**Comment by drnic** [comment]
Just tried this again today. Perhaps I'm using it wrong.

Failed job https://ci.starkandwayne.com/teams/main/pipelines/kafka-boshrelease/jobs/kafka/builds/2 which includes `0.11.0` rather than `0.11.0.1`.

Concourse pipeline:

```yaml
resource_types:
- name: apache-directory-index
  type: docker-image
  source:
    repository: mastertinner/apache-directory-index-resource
    tag: feature_support-longer-version-numbers

resources:
- name: kafka
  type: apache-directory-index
  source:
    directory: https://archive.apache.org/dist/kafka/
    folder_pattern: $VERSION
    file_pattern: kafka_2.12-$VERSION.tgz
```

**Comment by drnic** [comment]
Tried this today. I'm getting an error in the resource.

https://ci.starkandwayne.com/teams/main/pipelines/kafka-boshrelease/resources/kafka has an error:

```
resource script '/opt/resource/check []' failed: exit status 1

stderr:
/opt/resource/compare-versions.sh: line 63: $1: unbound variable
```

From my pipeline:

```yaml
resource_types:
- name: apache-directory-index
  type: docker-image
  source:
    repository: mastertinner/apache-directory-index-resource
    tag: feature_support-longer-version-numbers

resources:
- name: kafka
  type: apache-directory-index
  source:
    directory: https://archive.apache.org/dist/kafka
    folder_pattern: $VERSION
    file_pattern: kafka_2.12-$VERSION.tgz
```

**Comment by cloudlena** [comment]
Sorry. There was still a testing statement from me in there. Now it should work. Can you try again, @drnic?

**Comment by drnic** [comment]
Am getting error:

```
$ fly -t sw check-resource -r kafka-boshrelease/kafka
error: check failed with exit status '1':
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   246  100   246    0     0    246      0  0:00:01 --:--:--  0:00:01  1294
```

Not very help error message, sorry!

**Comment by cloudlena** [comment]
@drnic, I now have a local pipeline where I got it to work (after another fix). Please let me know if it now also works for you. Sorry for all the back and forth.

**Comment by drnic** [comment]
Hmm, I'm still getting the error above. I've tried deleting/recreating the pipeline; but I'm just unsure if concourse is actually fetching a newer docker image or not. You say it works; so now I'm questioning my concourse :/

So I created a new image based off your image, to try to ensure concourse was fetching it, but getting same error:

```
fly -t sw check-resource -r kafka-boshrelease/kafka
error: check failed with exit status '1':
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   246  100   246    0     0    246      0  0:00:01 --:--:--  0:00:01  1413
```

**Comment by drnic** [comment]
Can you do me a favour and share your test pipeline with a kafka example? I assume at this point I've misconfigured something (my config is as above)

**Comment by cloudlena** [comment]
It should be `directory: https://archive.apache.org/dist/kafka/` (with a slash at the end).

**Comment by drnic** [comment]
```
$ fly -t sw check-resource -r kafka-boshrelease/kafka
checked 'kafka'
```
Hurray!

**Comment by drnic** [comment]
screen shot 2017-10-31 at 10 29 06 am

Glorious `0.11.0.1` success!

**Comment by drnic** [comment]
Well done @mastertinner and thanks a lot!

**Comment by cloudlena** [comment]
Awesome! Thanks for your support, @drnic! I just merged it into `master`.

**Comment by drnic** [comment]
LOL. All this work to support v0.10.0.1 and the next version of kafka is semver `1.0.0`.

**Comment by cloudlena** [comment]
haha 😆  at least now we should be ready for anything they throw at us

**Pull request merged**
